### ISSUE TITLE
Regarding NLR Annotator meme suite version issue.

### ISSUE THREAD

**Issue by ank-man** [Daniel-Ze/exNLRs#1]
Greetings,
![MEMEERROR](https://user-images.githubusercontent.com/64264081/116079552-8c6a4c00-a6b5-11eb-9805-9bb03b5a654b.png)

I am having the same problem while installing older version of meme suite. I wonder how you resolved the issue as i saw your issue post on Burkhard's profile. Please guide me as the make command is showing some error most probably some bug in older version. 
Sincerely,
Ankush Sharma

**Comment by Daniel-Ze** [comment]
Hi Ankush,
from what I'm reading I would say there is some deprecated function. 
It says MPI_Adress() is not supported anymore and you should use MPI_Get_address().
The same seems to be the problem for MPI_Type_struct() which needs to be replaced with MPI_Type_create_struct(). 
But if this helps  I can't tell for certain.
This is some other problem compared to what I encountered.

Cheers
Daniel
